version: '2'
 
services:
 web:
   restart: always
   build: ./web
   expose:
     - "9000"
   volumes:
     - /usr/src/app/sms/static
   command: /usr/local/bin/gunicorn -c /usr/src/app/sms/gunicorn.conf.py wsgi:application
 
 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   volumes:
     - /www/static
   volumes_from:
     - web
   depends_on:
     - web
 
